import os
import tempfile
from datetime import datetime, timezone

from .config import settings
from .ips import list_enabled_values

HEADER = (
    "# Auto-generated by nginx-firewall. Do not edit by hand.\n"
    "# Last write: {ts}\n"
)


def render_allowlist() -> str:
    values = list_enabled_values()
    lines = [HEADER.format(ts=datetime.now(timezone.utc).isoformat(timespec="seconds"))]
    for v in values:
        lines.append(f"allow {v};\n")
    lines.append("deny all;\n")
    return "".join(lines)


def regenerate_allowlist() -> str:
    """Write the allowlist file atomically so inotify sees a single clean event."""
    content = render_allowlist()
    target = settings.allowlist_path
    target.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp_path = tempfile.mkstemp(prefix=".allowlist.", dir=str(target.parent))
    try:
        with os.fdopen(fd, "w") as f:
            f.write(content)
        os.replace(tmp_path, target)
    except Exception:
        try:
            os.unlink(tmp_path)
        except FileNotFoundError:
            pass
        raise
    return content
