import os
import tempfile
from datetime import datetime, timezone
from pathlib import Path

from .config import settings
from .ips import list_enabled_values
from .services import list_enabled_services

HEADER = (
    "# Auto-generated by nginx-firewall. Do not edit by hand.\n"
    "# Last write: {ts}\n"
)


def _ts() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def _write_atomic(target: Path, content: str) -> None:
    """Write a file atomically so inotify sees a single clean event."""
    target.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp_path = tempfile.mkstemp(prefix=".tmp.", dir=str(target.parent))
    try:
        with os.fdopen(fd, "w") as f:
            f.write(content)
        os.replace(tmp_path, target)
    except Exception:
        try:
            os.unlink(tmp_path)
        except FileNotFoundError:
            pass
        raise


def render_allowlist(service_id: int) -> str:
    values = list_enabled_values(service_id)
    lines = [HEADER.format(ts=_ts())]
    for v in values:
        lines.append(f"allow {v};\n")
    lines.append("deny all;\n")
    return "".join(lines)


def render_services_conf(services: list[dict]) -> str:
    parts = [HEADER.format(ts=_ts())]
    for s in services:
        allow_path = settings.allowlist_path(s["id"])
        listen = str(s["external_port"])
        if s["protocol"] == "udp":
            block = (
                f"# {s['name']} (udp)\n"
                "server {\n"
                f"    listen {listen} udp;\n"
                f"    include {allow_path};\n"
                f"    proxy_pass {s['upstream_host']}:{s['target_port']};\n"
                "    proxy_timeout 30s;\n"
                "    proxy_responses 0;\n"
                "}\n"
            )
        else:
            block = (
                f"# {s['name']} (tcp)\n"
                "server {\n"
                f"    listen {listen};\n"
                f"    include {allow_path};\n"
                f"    proxy_pass {s['upstream_host']}:{s['target_port']};\n"
                "    proxy_connect_timeout 5s;\n"
                "}\n"
            )
        parts.append(block)
    return "\n".join(parts)


def regenerate() -> str:
    """Rewrite every per-service allowlist plus the stream server blocks.

    Ordering matters so nginx never reloads a config that `include`s a file
    that isn't there yet:
      1. write each enabled service's allowlist (referenced by its block),
      2. write services.conf last (references those allowlists),
      3. delete allowlists for services that no longer exist.
    Deletes don't trigger inotify, and step 2's file only ever references
    allowlists written in step 1, so every reload sees a consistent set.
    """
    services = list_enabled_services()

    keep = set()
    for s in services:
        path = settings.allowlist_path(s["id"])
        _write_atomic(path, render_allowlist(s["id"]))
        keep.add(path.name)

    content = render_services_conf(services)
    _write_atomic(settings.services_conf_path, content)

    _cleanup_orphans(keep)
    return content


def _cleanup_orphans(keep: set[str]) -> None:
    dynamic_dir = settings.dynamic_dir
    if not dynamic_dir.exists():
        return
    for f in dynamic_dir.glob("svc-*.allow.conf"):
        if f.name not in keep:
            try:
                f.unlink()
            except FileNotFoundError:
                pass
