#!/bin/sh
set -eu

# The stream server blocks are generated by the FastAPI app into the shared
# volume, so nginx itself needs no upstream env vars. We just install the base
# config and make sure the generated includes exist before validating.
cp /etc/nginx/nginx.conf.template /etc/nginx/nginx.conf

mkdir -p /etc/nginx/dynamic
if [ ! -f /etc/nginx/dynamic/services.conf ]; then
    printf '# No services configured yet.\n' > /etc/nginx/dynamic/services.conf
fi

# Validate the base config before starting. With no services yet the stream
# block is empty, which is valid.
nginx -t

# Watch the generated config (services.conf + per-service allowlists) and
# reload nginx on changes. The FastAPI service writes atomically (tempfile +
# os.replace), so close_write/moved_to fires once per change with a valid file
# already in place.
(
    while inotifywait -e close_write,moved_to,create /etc/nginx/dynamic 2>/dev/null; do
        if nginx -t 2>/tmp/nginx-test.err; then
            nginx -s reload
            echo "[reloader] reloaded nginx at $(date -Iseconds)"
        else
            echo "[reloader] config invalid, keeping previous:" >&2
            cat /tmp/nginx-test.err >&2
        fi
    done
) &

exec nginx -g 'daemon off;'
